### ISSUE TITLE
Issue when using pip

### ISSUE THREAD

**Issue by HyronNotEZ** [JeanExtreme002/PyMemoryEditor#1]
Hey there, I found your library and wanted to give it a shot. Sadly i get this error when i try to install it with pip. 
```
Collecting PyMemoryEditor
  Using cached PyMemoryEditor-1.0.1.tar.gz (8.9 kB)
  Using cached PyMemoryEditor-1.0.0.tar.gz (8.8 kB)

C:\PythonScripts\venv\lib\site-packages\secretstorage\dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
C:\PythonScripts\venv\lib\site-packages\secretstorage\util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
    ERROR: Command errored out with exit status 1:
     command: 'C:\PythonScripts\venv\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Stephan\\AppData\\Local\\Temp\\pip-install-gqj_swgx\\pymemoryeditor_050413fbc9c7458a9b65714938878af2\\setup.py'"'"'; __file__='"'"'C:\\Users\\Stephan\\AppData\\Local\\Temp\\pip-install-gqj_swgx\\pymemoryeditor_050413fbc9c7458a9b65714938878af2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Stephan\AppData\Local\Temp\pip-pip-egg-info-ooyckyr2'
         cwd: C:\Users\Stephan\AppData\Local\Temp\pip-install-gqj_swgx\pymemoryeditor_050413fbc9c7458a9b65714938878af2\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Stephan\AppData\Local\Temp\pip-install-gqj_swgx\pymemoryeditor_050413fbc9c7458a9b65714938878af2\setup.py", line 3, in <module>
        from PyMemoryEditor import __version__
      File "C:\Users\Stephan\AppData\Local\Temp\pip-install-gqj_swgx\pymemoryeditor_050413fbc9c7458a9b65714938878af2\PyMemoryEditor\__init__.py", line 11, in <module>
        from .process import Process
      File "C:\Users\Stephan\AppData\Local\Temp\pip-install-gqj_swgx\pymemoryeditor_050413fbc9c7458a9b65714938878af2\PyMemoryEditor\process\__init__.py", line 4, in <module>
        from .util import get_process_id_by_process_name, get_process_id_by_window_title, pid_exists
      File "C:\Users\Stephan\AppData\Local\Temp\pip-install-gqj_swgx\pymemoryeditor_050413fbc9c7458a9b65714938878af2\PyMemoryEditor\process\util.py", line 3, in <module>
        from win32gui import FindWindow
    ModuleNotFoundError: No module named 'win32gui'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/74/81/5c8d3976b2848dd53ea727d223e5d4eab3eb006cdf416857d69fcf4b03c2/PyMemoryEditor-1.0.1.tar.gz#sha256=780317b41a217b08fadc9c676aa177f90ca86bdb5a930e73c1a8e9ce6ac147ea (from https://pypi.org/simple/pymemoryeditor/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: 'C:\PythonScripts\venv\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Stephan\\AppData\\Local\\Temp\\pip-install-gqj_swgx\\pymemoryeditor_32ccc9919d69435085226baba88986be\\setup.py'"'"'; __file__='"'"'C:\\Users\\Stephan\\AppData\\Local\\Temp\\pip-install-gqj_swgx\\pymemoryeditor_32ccc9919d69435085226baba88986be\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Stephan\AppData\Local\Temp\pip-pip-egg-info-du7jun_s'
         cwd: C:\Users\Stephan\AppData\Local\Temp\pip-install-gqj_swgx\pymemoryeditor_32ccc9919d69435085226baba88986be\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Stephan\AppData\Local\Temp\pip-install-gqj_swgx\pymemoryeditor_32ccc9919d69435085226baba88986be\setup.py", line 3, in <module>
        from PyMemoryEditor import __version__
      File "C:\Users\Stephan\AppData\Local\Temp\pip-install-gqj_swgx\pymemoryeditor_32ccc9919d69435085226baba88986be\PyMemoryEditor\__init__.py", line 11, in <module>
        from .process import Process
      File "C:\Users\Stephan\AppData\Local\Temp\pip-install-gqj_swgx\pymemoryeditor_32ccc9919d69435085226baba88986be\PyMemoryEditor\process\__init__.py", line 4, in <module>
        from .util import get_process_id_by_process_name, get_process_id_by_window_title, pid_exists
      File "C:\Users\Stephan\AppData\Local\Temp\pip-install-gqj_swgx\pymemoryeditor_32ccc9919d69435085226baba88986be\PyMemoryEditor\process\util.py", line 3, in <module>
        from win32gui import FindWindow
    ModuleNotFoundError: No module named 'win32gui'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/1d/8f/5f7aa65f0ad10fdc93e76075922d4c6e92100a763eb0a7237f06ef74d646/PyMemoryEditor-1.0.0.tar.gz#sha256=7382f832841047a7707b96821224fb42a4f7c78cc0db35c4cea5240fe538b7d4 (from https://pypi.org/simple/pymemoryeditor/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement PyMemoryEditor
ERROR: No matching distribution found for PyMemoryEditor
```

**Comment by JeanExtreme002** [comment]
Hello @HyronNotEZ , sorry for the delay. Could you tell me how you are installing the package? And what version of Python are you using?
