### ISSUE TITLE
Pip Install missing Module

### ISSUE THREAD

**Issue by levantocode** [JeanExtreme002/PyMemoryEditor#2]
Hey, I'm having trouble to find a recent python library that reads memory... and finally found yours :)
But when I try to install it with pip as instructed in the readme, I get a big error that resumes in "ModuleNotFoundError: No module named 'psutil'". Hope it can get fixed soon! ty

## Full Stacktrace:

```
"ERROR: Command errored out with exit status 1:
     command: 'c:\users\caioc\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\caioc\\AppData\\Local\\Temp\\pip-install-hglfu2zq\\pymemoryeditor_a167eaa3425c468d8cf90f12fc053e8c\\setup.py'"'"'; __file__='"'"'C:\\Users\\caioc\\AppData\\Local\\Temp\\pip-install-hglfu2zq\\pymemoryeditor_a167eaa3425c468d8cf90f12fc053e8c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\caioc\AppData\Local\Temp\pip-pip-egg-info-gubp11kt'
         cwd: C:\Users\caioc\AppData\Local\Temp\pip-install-hglfu2zq\pymemoryeditor_a167eaa3425c468d8cf90f12fc053e8c\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\caioc\AppData\Local\Temp\pip-install-hglfu2zq\pymemoryeditor_a167eaa3425c468d8cf90f12fc053e8c\setup.py", line 3, in <module>
        from PyMemoryEditor import __version__
      File "C:\Users\caioc\AppData\Local\Temp\pip-install-hglfu2zq\pymemoryeditor_a167eaa3425c468d8cf90f12fc053e8c\PyMemoryEditor\__init__.py", line 11, in <module>
        from .process import Process
      File "C:\Users\caioc\AppData\Local\Temp\pip-install-hglfu2zq\pymemoryeditor_a167eaa3425c468d8cf90f12fc053e8c\PyMemoryEditor\process\__init__.py", line 4, in <module>
        from .util import get_process_id_by_process_name, get_process_id_by_window_title, pid_exists
      File "C:\Users\caioc\AppData\Local\Temp\pip-install-hglfu2zq\pymemoryeditor_a167eaa3425c468d8cf90f12fc053e8c\PyMemoryEditor\process\util.py", line 5, in <module>
        import psutil
    ModuleNotFoundError: No module named 'psutil'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output."
```

**Comment by JeanExtreme002** [comment]
Hello @levantocode. Apparently the `psutil` package does not support Python version 3.9. Try to install `PyMemoryEditor` using one of these versions: 3.6, 3.7, 3.8.
